### ISSUE TITLE
Perubahan logo Darmajaya

### ISSUE THREAD

**Issue by h4rys4b1t4** [sasriawesome/intradarmajaya#17]
Logo darmajaya diubah/ revisi sesuai dengan logo standar hasil rebranding

**Comment by sasriawesome** [comment]
yg mana ?

**Comment by h4rys4b1t4** [comment]
https://drive.google.com/drive/folders/1DfUx3mcjbyh12yV5HLILS090aMH3heuN?usp=sharing

**Comment by h4rys4b1t4** [comment]
ada 10 logo di situ, kalau gw sir yg Logo Darmajaya Vertical 01
